### ISSUE TITLE
Export / Import

### ISSUE THREAD

**Issue by markmaas** [filidorwiese/gnome-shell-crypto-stash#1]
Hi Filidor!

Is it possible to make an export and import feature? I'd like to reinstall my machine (Pop!_os 21.04) and DESPERATELY want to keep this extension #ofcourse.

;-P

**Comment by filidorwiese** [comment]
Hi Mark, I'm so pleased you like the extension! 🤗

At the moment there is no import/export functionality, but it is a great idea to be able to be able to backup your data, I'll think about it. For now, you could use the dconf-editor to read the internal database and copy that to the new OS:

```
$ dconf-editor /org/gnome/shell/extensions/crypto-stash/
```

Your crypto data is all there :point_up:. After installing the extension on the new machine, simply open dconf-editor again and overwrite the value.

**Comment by markmaas** [comment]
Hey! That is awesome, and also works (I see now) for all other extensions as well!
